# Generated by Django 4.2 on 2026-07-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
