# Generated by Django 4.2 on 2026-07-11 15:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_alter_service_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="max_capacity",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
