# Generated by Django 4.2 on 2026-07-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0005_alter_service_buffer_after_minutes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="update_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
