# Generated by Django 4.2 on 2026-07-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0006_service_update_at"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="service",
            constraint=models.CheckConstraint(
                check=models.Q(("price__gte", 0)), name="service_price_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="service",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("duration_minutes__isnull", True),
                    ("duration_minutes__gte", 1),
                    _connector="OR",
                ),
                name="service_duration_null_or_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="service",
            constraint=models.CheckConstraint(
                check=models.Q(("buffer_before_minutes__gte", 0)),
                name="service_buffer_before_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="service",
            constraint=models.CheckConstraint(
                check=models.Q(("buffer_after_minutes__gte", 0)),
                name="service_buffer_after_gte_0",
            ),
        ),
    ]
