# Generated by Django 4.2 on 2026-07-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0007_service_service_price_gte_0_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="service",
            constraint=models.CheckConstraint(
                check=models.Q(("max_capacity__gte", 1)),
                name="service_max_capacity_gte_1",
            ),
        ),
    ]
