# Generated by Django 4.2 on 2026-07-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0008_service_service_max_capacity_gte_1"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["company", "is_active"], name="service_company_active_idx"
            ),
        ),
    ]
