# Generated by Django 4.2 on 2026-07-11 15:56

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0009_service_service_company_active_idx"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="service",
            name="service_duration_null_or_gte_1",
        ),
        migrations.AlterField(
            model_name="service",
            name="duration_minutes",
            field=models.PositiveIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="service",
            constraint=models.CheckConstraint(
                check=models.Q(("duration_minutes__gte", 1)),
                name="service_duration_gte_1",
            ),
        ),
    ]
