# Generated by Django 4.2 on 2026-07-12 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0007_remove_company_cancellation_policy_text"),
        ("services", "0010_remove_service_service_duration_null_or_gte_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="services",
                to="companies.company",
            ),
        ),
    ]
