# Generated by Django 4.2 on 2026-07-15 14:14

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0011_alter_service_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="fixed_guest_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Required guest count when the service has a fixed guest count",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="guest_count_policy",
            field=models.CharField(
                choices=[
                    ("variable", "Customer select guest count"),
                    ("fixed", "Fixed guest count"),
                ],
                default="variable",
                help_text="Determines whether the customer can select guest count",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="minimum_billable_guest",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Number of guest that include in the best price",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="price_per_guest",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Price charged for each guest above the minimum billable guest count",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
