# Generated by Django 4.2 on 2026-07-31 13:44

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0007_remove_company_cancellation_policy_text"),
        (
            "services",
            "0012_service_fixed_guest_count_service_guest_count_policy_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ServicePackageItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="service-specific price. Empty means use the service's normal price.",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("required", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ServicePackages",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "pricing_method",
                    models.CharField(
                        choices=[
                            ("service_total", "Sum of service prices"),
                            ("fixed_price", "Fixed package price"),
                            ("percentage_discount", "percentage discount"),
                            ("fixed_discount", "fixed discount"),
                        ],
                        default="service_total",
                        max_length=20,
                    ),
                ),
                (
                    "fixed_discount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "percentage_discount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "fixed_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Final package price, regardless of included service prices.",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("allow_full_payment", models.BooleanField(default=True)),
                (
                    "deposit_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Leave empty if deposit payments are not available. Example: enter 20 for a 20% deposit.",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("99.99")),
                        ],
                    ),
                ),
                (
                    "installment_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount of each installment. Leave empty if installments are not available.",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "installment_interval",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("weekly", "Weekly"),
                            ("biweekly", "Every two weeks"),
                            ("monthly", "Monthly"),
                        ],
                        help_text="Frequency of installment payments. Required when an installment amount is configured.",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("allow_scheduling_late", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Service package",
                "verbose_name_plural": "Service packages",
                "ordering": ["name"],
            },
        ),
        migrations.AddConstraint(
            model_name="service",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("minimum_billable_guest__gte", 1),
                    ("minimum_billable_guest__lte", models.F("max_capacity")),
                ),
                name="svc_min_billable_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="service",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("fixed_guest_count__isnull", True),
                        ("guest_count_policy", "variable"),
                    ),
                    models.Q(
                        ("guest_count_policy", "fixed"),
                        ("fixed_guest_count__isnull", False),
                        ("fixed_guest_count__gte", 1),
                        ("fixed_guest_count__lte", models.F("max_capacity")),
                    ),
                    _connector="OR",
                ),
                name="svc_fixed_guest_valid",
            ),
        ),
        migrations.AddField(
            model_name="servicepackages",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="service_packages",
                to="companies.company",
            ),
        ),
        migrations.AddField(
            model_name="servicepackages",
            name="services",
            field=models.ManyToManyField(
                related_name="package",
                through="services.ServicePackageItem",
                to="services.service",
            ),
        ),
        migrations.AddField(
            model_name="servicepackageitem",
            name="package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="services.servicepackages",
            ),
        ),
        migrations.AddField(
            model_name="servicepackageitem",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="package_items",
                to="services.service",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicepackages",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("allow_full_payment", True),
                    ("deposit_percentage__isnull", False),
                    ("installment_amount__isnull", False),
                    _connector="OR",
                ),
                name="service_package_has_payment_plan",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicepackages",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("deposit_percentage__isnull", True),
                    models.Q(
                        ("deposit_percentage__gt", Decimal("0.00")),
                        ("deposit_percentage__lt", Decimal("100.00")),
                    ),
                    _connector="OR",
                ),
                name="service_package_valid_deposit_percentage",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicepackages",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("installment_amount__isnull", True),
                        ("installment_interval__isnull", True),
                    ),
                    models.Q(
                        ("installment_amount__gt", Decimal("0.00")),
                        ("installment_interval__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="service_package_valid_installment_configuration",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicepackageitem",
            constraint=models.UniqueConstraint(
                fields=("package", "service"), name="unique_service_per_package"
            ),
        ),
    ]
