# Generated by Django 4.2 on 2026-08-02 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0013_servicepackageitem_servicepackages_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicepackages",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="package",
                to="services.servicecategory",
            ),
            preserve_default=False,
        ),
    ]
