# Generated by Django 4.2 on 2026-05-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_options_companylocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='companylocation',
            name='city',
            field=models.CharField(default='shiraz', max_length=100),
        ),
        migrations.AlterField(
            model_name='companylocation',
            name='country',
            field=models.CharField(max_length=100),
        ),
    ]
