# Generated by Django 4.2 on 2026-05-18 18:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0005_companylocation_city_alter_companylocation_country"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyWorkingHours",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(6),
                        ],
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="working_hours",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Working Hour",
                "verbose_name_plural": "Working Hours",
                "db_table": "company_working_hours",
                "ordering": ["weekday", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="CompanyTimeOff",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                ("reason", models.CharField(blank=True, max_length=255)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_offs",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Time Off",
                "verbose_name_plural": "Time Off",
                "db_table": "company_time_off",
                "ordering": ["start_datetime"],
            },
        ),
        migrations.CreateModel(
            name="CompanyCancellationPolicyRules",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rule_description", models.CharField(max_length=255)),
                ("hours_before_event", models.PositiveIntegerField()),
                (
                    "refund_precentage",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("priority", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cancellation_policy",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cancellation Policy Rule",
                "verbose_name_plural": "Cancellation Policy Rules",
                "db_table": "company_cancellation_policy_rules",
                "ordering": ["priority", "hours_before_event"],
            },
        ),
        migrations.AddConstraint(
            model_name="companyworkinghours",
            constraint=models.UniqueConstraint(
                fields=("company", "weekday", "start_time", "end_time"),
                name="unique_company_working_hours",
            ),
        ),
        migrations.AddConstraint(
            model_name="companyworkinghours",
            constraint=models.CheckConstraint(
                check=models.Q(("start_time__lt", models.F("end_time"))),
                name="working_hours_start_before_end",
            ),
        ),
        migrations.AddConstraint(
            model_name="companytimeoff",
            constraint=models.CheckConstraint(
                check=models.Q(("start_datetime__lt", models.F("end_datetime"))),
                name="time_off_start_before_end",
            ),
        ),
    ]
