# Generated by Django 4.2 on 2026-05-22 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0006_companyworkinghours_companytimeoff_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="cancellation_policy_text",
        ),
    ]
