# Generated by Django 4.2 on 2026-06-01 16:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='event_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='event_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_option',
            field=models.CharField(choices=[('REQUEST_BOOKING_FIRST', 'Request booking first'), ('PAY_DEPOSIT_LATER', 'Pay deposit later'), ('PAY_FULL_AMOUNT_LATER', 'Pay full amount later'), ('PAY_FULL_AMOUNT_NOW', 'Pay full amount now'), ('PAY_DEPOSIT_NOW', 'Pay deposit now')], default='REQUEST_BOOKING_FIRST', max_length=40),
        ),
    ]
