# Generated by Django 4.2 on 2026-06-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_event_date_booking_event_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='event_type',
            field=models.CharField(default='wedding', max_length=255),
            preserve_default=False,
        ),
    ]
