# Generated by Django 4.2 on 2026-06-03 13:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='event_end_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
