# Generated by Django 4.2 on 2026-06-04 13:45

from django.db import migrations


def update_canceled_to_cancelled(apps, schema_editor):
    Booking = apps.get_model("booking", "Booking")
    Booking.objects.filter(status="CANCELED").update(status="CANCELLED")


def reverse_cancelled_to_canceled(apps, schema_editor):
    Booking = apps.get_model("booking", "Booking")
    Booking.objects.filter(status="CANCELLED").update(status="CANCELED")


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0004_booking_event_end_time"),
    ]

    operations = [
        migrations.RunPython(
            update_canceled_to_cancelled,
            reverse_cancelled_to_canceled,
        ),
    ]
