# Generated by Django 4.2 on 2026-07-12 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0007_alter_booking_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="guest_numbers",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Guest number minimum value is 1"
                    )
                ]
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                check=models.Q(("guest_numbers__gte", 1)),
                name="booking_guest_numbers_gte_1",
            ),
        ),
    ]
