# Generated by Django 4.2 on 2026-07-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0008_alter_booking_guest_numbers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="ends_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="starts_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
