# Generated by Django 4.2 on 2026-07-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0010_populate_booking_datetimes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="ends_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="booking",
            name="starts_at",
            field=models.DateTimeField(),
        ),
    ]
