# Generated by Django 4.2 on 2026-07-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0011_alter_booking_ends_at_alter_booking_starts_at"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                check=models.Q(("ends_at__gt", models.F("starts_at"))),
                name="booking_ends_at_after_starts_at",
            ),
        ),
    ]
