# Generated by Django 4.2 on 2026-07-12 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0012_booking_booking_ends_at_after_starts_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="event_date",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="event_end_time",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="event_time",
        ),
    ]
