# Generated by Django 4.2 on 2026-07-12 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0013_remove_booking_event_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="category",
        ),
    ]
