# Generated by Django 4.2 on 2026-07-12 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0011_alter_service_company"),
        ("booking", "0014_remove_booking_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="services.service",
            ),
        ),
    ]
