# Generated by Django 4.2 on 2026-07-12 16:01

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("booking", "0015_alter_booking_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="cancelled_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="contact_detail_email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="booking",
            name="contact_detail_phone_number",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="booking",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="booking",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="booking",
            name="refund_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        Decimal("0.00"), message="Refund amount cannot be negetive"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="special_request",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        Decimal("0.00"), message="Total price cannot be negetive"
                    )
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                check=models.Q(("total_price__gte", 0)),
                name="booking_total_price_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("deposit_amount__isnull", True),
                    ("deposit_amount__gte", 0),
                    _connector="OR",
                ),
                name="booking_deposit_null_or_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                check=models.Q(("refund_amount__gte", 0)),
                name="booking_refund_amount_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("deposit_amount__isnull", True),
                    ("deposit_amount__lte", models.F("total_price")),
                    _connector="OR",
                ),
                name="booking_deposit_lte_total_price",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                check=models.Q(("refund_amount__lte", models.F("total_price"))),
                name="booking_refund_lte_total_price",
            ),
        ),
    ]
